/*
 * FrmTrangulo.java
 *
 * Created on 11 de marzo de 2008, 04:27 PM
 */
package geometria3.gui;

import geometria3.mundo.Triangulo;

/**
 *
 * @author  guavita
 */
public class FrmTrangulo extends javax.swing.JFrame {

    private Triangulo triangulo;

    /** Creates new form FrmTrangulo */
    public FrmTrangulo(Triangulo triangulo) {
        initComponents();
        this.triangulo = triangulo;
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelAdorno = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        cmdModificarTriangulo = new javax.swing.JButton();
        cmdDeterminarTipo = new javax.swing.JButton();
        cmdAyuda = new javax.swing.JButton();
        paneDatos = new javax.swing.JPanel();
        lblLado1 = new javax.swing.JLabel();
        txtLado1 = new javax.swing.JTextField();
        lblLado2 = new javax.swing.JLabel();
        txtLado2 = new javax.swing.JTextField();
        lblLado3 = new javax.swing.JLabel();
        txtLado3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tipos de Triángulo");
        setResizable(false);

        panelTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelTitulo.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 36));
        jLabel2.setText("Tipos de Triángulo");
        panelTitulo.add(jLabel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelTitulo, java.awt.BorderLayout.NORTH);

        panelAdorno.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblImagen.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        lblImagen.setForeground(new java.awt.Color(0, 0, 255));
        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pitagoras.jpg"))); // NOI18N
        lblImagen.setText("Tipo Desconocido");
        lblImagen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblImagen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelAdorno.add(lblImagen);

        getContentPane().add(panelAdorno, java.awt.BorderLayout.EAST);

        panelBotones.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelBotones.setLayout(new java.awt.GridLayout(1, 3));

        cmdModificarTriangulo.setText("Actualizar Medidas");
        cmdModificarTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdModificarTrianguloActionPerformed(evt);
            }
        });
        panelBotones.add(cmdModificarTriangulo);

        cmdDeterminarTipo.setText("Determinar Tipo");
        cmdDeterminarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeterminarTipoActionPerformed(evt);
            }
        });
        panelBotones.add(cmdDeterminarTipo);

        cmdAyuda.setText("Ayuda");
        cmdAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAyudaActionPerformed(evt);
            }
        });
        panelBotones.add(cmdAyuda);

        getContentPane().add(panelBotones, java.awt.BorderLayout.SOUTH);

        paneDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        paneDatos.setLayout(new java.awt.GridLayout(3, 2));

        lblLado1.setText("Lado 1:");
        lblLado1.setBorder(null);
        paneDatos.add(lblLado1);

        txtLado1.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        txtLado1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLado1.setText("0.0");
        txtLado1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        paneDatos.add(txtLado1);

        lblLado2.setText("Lado 2:");
        lblLado2.setBorder(null);
        paneDatos.add(lblLado2);

        txtLado2.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        txtLado2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLado2.setText("0.0");
        txtLado2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        paneDatos.add(txtLado2);

        lblLado3.setText("Lado 3:");
        lblLado3.setBorder(null);
        paneDatos.add(lblLado3);

        txtLado3.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        txtLado3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLado3.setText("0.0");
        txtLado3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        paneDatos.add(txtLado3);

        getContentPane().add(paneDatos, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cmdDeterminarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeterminarTipoActionPerformed
        lblImagen.setText(triangulo.getTipo());
}//GEN-LAST:event_cmdDeterminarTipoActionPerformed

    private void cmdModificarTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdModificarTrianguloActionPerformed
        triangulo.setLado1(Float.parseFloat(txtLado1.getText()));
        triangulo.setLado2(Float.parseFloat(txtLado2.getText()));
        triangulo.setLado3(Float.parseFloat(txtLado3.getText()));
        lblImagen.setText("Tipo Desconocido");
        javax.swing.JOptionPane.showMessageDialog(this, "Medidas Actualizadas");
}//GEN-LAST:event_cmdModificarTrianguloActionPerformed

    private void cmdAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAyudaActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Determina el tipo de Triangulo.");
    }//GEN-LAST:event_cmdAyudaActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAyuda;
    private javax.swing.JButton cmdDeterminarTipo;
    private javax.swing.JButton cmdModificarTriangulo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblLado1;
    private javax.swing.JLabel lblLado2;
    private javax.swing.JLabel lblLado3;
    private javax.swing.JPanel paneDatos;
    private javax.swing.JPanel panelAdorno;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTextField txtLado1;
    private javax.swing.JTextField txtLado2;
    private javax.swing.JTextField txtLado3;
    // End of variables declaration//GEN-END:variables
}
